export const RECEIVE_MATCHES = 'RECEIVE_MATCHES'
export const REQUEST_MATCHES = 'REQUEST_MATCHES'

export const REQUEST_SCORES = 'REQUEST_SCORES'
export const RECEIVE_SCORES = 'RECEIVE_SCORES'

export const REQUEST_STANDINGS = 'REQUEST_STANDINGS'
export const RECEIVE_STANDINGS = 'RECEIVE_STANDINGS'

export const REQUEST_PLAYER = 'REQUEST_PLAYER'
export const RECEIVE_PLAYER = 'RECEIVE_PLAYER'

export const REQUEST_ROSTER = 'REQUEST_ROSTER'
export const RECEIVE_ROSTER = 'RECEIVE_ROSTER'

export const REQUEST_LINEUP = 'REQUEST_LINEUP'
export const RECEIVE_LINEUP = 'RECEIVE_LINEUP'

export const POST_NEW_LINEUP = 'POST_NEW_LINEUP'
export const POST_NEW_LINEUP_SUCCESS = 'POST_NEW_LINEUP_SUCCESS'
export const POST_NEW_LINEUP_DONE = 'POST_NEW_LINEUP_DONE'
export const POST_NEW_LINEUP_FAILURE = 'POST_NEW_LINEUP_FAILURE'
export const UPDATE_LOCAL_LINEUP = 'UPDATE_LOCAL_LINEUP'
export const CREATE_LOCAL_LINEUP = 'CREATE_LOCAL_LINEUP'

export const UPDATE_MATCH_STATUS = 'UPDATE_MATCH_STATUS'
export const UPDATE_USER_SCHEDULE_STATUS = 'UPDATE_USER_SCHEDULE_STATUS'

export const SET_FETCHED_TEAMS = 'SET_FETCHED_TEAMS'
export const LOG_IN_PLAYER = 'LOG_IN_PLAYER'

export const CAPTAIN_TEAMS = 'CAPTAIN_TEAMS'
export const SUBSCRIBE_CAPTAIN = 'SUBSCRIBE_CAPTAIN'
export const SUBSCRIBE_CAPTAIN_SUCCESS = 'SUBSCRIBE_CAPTAIN_SUCCESS'
export const SUBSCRIBE_CAPTAIN_FAILURE = 'SUBSCRIBE_CAPTAIN_FAILURE'
export const SUBSCRIBE_CAPTAIN_DONE = 'SUBSCRIBE_CAPTAIN_DONE'

export const ACTIVATED_TEAMS = 'ACTIVATED_TEAMS'
export const USER_SCHEDULE_STATUS = 'USER_SCHEDULE_STATUS'

export const REQUEST_SUBSCRIPTIONS = 'REQUEST_SUBSCRIPTIONS'
export const RECEIVE_SUBSCRIPTIONS = 'RECEIVE_SUBSCRIPTIONS'
export const SUBSCRIBE_PLAYER = 'SUBSCRIBE_PLAYER'
export const SUBSCRIBE_PLAYER_SUCCESS = 'SUBSCRIBE_PLAYER_SUCCESS'
export const SUBSCRIBE_PLAYER_FAILURE = 'SUBSCRIBE_PLAYER_FAILURE'
export const SUBSCRIBE_PLAYER_DONE = 'SUBSCRIBE_PLAYER_DONE'

export const BUY_TEAMS = 'BUY_TEAMS'
export const UPDATE_UNUSED_TEAMS_SUCCESS = 'UPDATE_UNUSED_TEAMS_SUCCESS'
export const UPDATE_UNUSED_TEAMS_FAILURE = 'UPDATE_UNUSED_TEAMS_FAILURE'

export const USER_LOGOUT = 'USER_LOGOUT'

export const SCHEDULE_MAP = 'SCHEDULE_MAP'
